"""Standardized Error Codes."""
from enum import Enum

class ErrorCode(str, Enum):
    # Common
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_PAGINATION = "INVALID_PAGINATION"
    INVALID_FILTER = "INVALID_FILTER"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    
    # Protection
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    PROTECTION_REJECTED = "PROTECTION_REJECTED"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    QUERY_TOO_LARGE = "QUERY_TOO_LARGE"
    CONCURRENCY_LIMIT = "CONCURRENCY_LIMIT"
    RATE_LIMITER_UNAVAILABLE = "RATE_LIMITER_UNAVAILABLE"
    SECURITY_CONFIGURATION_ERROR = "SECURITY_CONFIGURATION_ERROR"
    
    # Auth
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    
    # Domain Not Found
    AREA_NOT_FOUND = "AREA_NOT_FOUND"
    PREDICTION_NOT_FOUND = "PREDICTION_NOT_FOUND"
    ALERT_NOT_FOUND = "ALERT_NOT_FOUND"
    NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
    
    # Domain Invalid
    INVALID_COORDINATE = "INVALID_COORDINATE"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
