"""Contract definitions for Collectors and Providers."""
from typing import Protocol, runtime_checkable, Any

@runtime_checkable
class CollectorContract(Protocol):
    async def connect(self) -> None: ...
    async def fetch(self, **kwargs) -> Any: ...
    async def parse(self, raw_data: Any) -> Any: ...
    async def normalize(self, parsed_data: Any) -> Any: ...
    async def validate(self, normalized_data: Any) -> bool: ...
    async def health(self) -> bool: ...
    async def metadata(self) -> dict: ...
    async def disconnect(self) -> None: ...
